version: '2'
services:

    db:
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - backend_network
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234

networks:
  backend_network: