version: '2'
services:

    db:
      image: postgres
      ports:
        - "5432:5432"
      networks:
        - backend_network
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=1234

#    rabbit:
#        hostname: rabbit
#        image: rabbitmq:latest
#        environment:
#          - RABBITMQ_DEFAULT_USER=admin
#          - RABBITMQ_DEFAULT_PASS=mypass
#        ports:
#            - "5672:5672"
#    backend:
#      image: myapi
#      depends_on:
#        - rabbit
#      networks:
#        - backend_network
#      environment:
#        - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672
#        - GMAIL_USER=$GMAIL_USER
#        - GMAIL_PASS=$GMAIL_PASS
#      entrypoint: ["/bin/sh", "./entrypoint/start.sh"]
#      ports:
#        - "8000:8000"
#
#    worker:
#       image: myapi
#       networks:
#         - backend_network
#       environment:
#         - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672
#       depends_on:
#         - backend
#         - rabbit
#       entrypoint: ["/bin/sh", "./entrypoint/worker.sh"]
#       links:
#            - rabbit
#
#    flower:
#        image: myapi
#        networks:
#          - backend_network
#        environment:
#          - CELERY_BROKER_URL=amqp://admin:mypass@rabbit:5672
#        command: ["/bin/sh", "./entrypoint/flower.sh"]
#        depends_on:
#            - rabbit
#            - worker
#        ports:
#            - "5555:5555"
#
networks:
  backend_network: