apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"name":"worker"},"name":"worker","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"service":"worker"}},"template":{"metadata":{"labels":{"service":"worker"}},"spec":{"containers":[{"args":["celery worker -A flask_app.worker.tasks.celery_app --broker=$CELERY_BROKER_URL --loglevel=info --autoscale=5,1","flower -A flask_app.worker.tasks.celery_app --broker=$CELERY_BROKER_URL --port=5555"],"command":["/bin/bash","-c"],"env":[{"name":"USER","valueFrom":{"secretKeyRef":{"key":"user","name":"postgres-credentials"}}},{"name":"PASS","valueFrom":{"secretKeyRef":{"key":"password","name":"postgres-credentials"}}},{"name":"IP","value":"postgres"},{"name":"SECRET_CODE","value":"19941116"},{"name":"DB","valueFrom":{"secretKeyRef":{"key":"user","name":"postgres-credentials"}}},{"name":"BROKER_USER","valueFrom":{"secretKeyRef":{"key":"rabbitmq_user","name":"flask-credentials"}}},{"name":"BROKER_PASS","valueFrom":{"secretKeyRef":{"key":"rabbitmq_pass","name":"flask-credentials"}}},{"name":"CELERY_BROKER_URL","value":"amqp://$(BROKER_USER):$(BROKER_PASS)@rabbitmq-service:5672"}],"image":"docker.pkg.github.com/claudezss/myapi/backend:1.0.4","imagePullPolicy":"Always","lifecycle":{"postStart":{"exec":{"command":["/bin/bash","-c","echo 123123"]}}},"name":"worker"}],"imagePullSecrets":[{"name":"dockerconfigjson-github-com"}],"restartPolicy":"Always"}}}}
  creationTimestamp: null
  generation: 1
  labels:
    name: worker
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:name: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:service: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:service: {}
          f:spec:
            f:containers:
              k:{"name":"worker"}:
                .: {}
                f:args: {}
                f:command: {}
                f:env:
                  .: {}
                  k:{"name":"BROKER_PASS"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"BROKER_USER"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"CELERY_BROKER_URL"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"DB"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"IP"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"PASS"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"SECRET_CODE"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"USER"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:secretKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:lifecycle:
                  .: {}
                  f:postStart:
                    .: {}
                    f:exec:
                      .: {}
                      f:command: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:imagePullSecrets:
              .: {}
              k:{"name":"dockerconfigjson-github-com"}:
                .: {}
                f:name: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: kubectl
    operation: Update
    time: "2020-10-19T01:27:18Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2020-10-19T01:27:21Z"
  name: worker
  selfLink: /apis/apps/v1/namespaces/default/deployments/worker
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      service: worker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: worker
    spec:
      containers:
      - args:
        - celery worker -A flask_app.worker.tasks.celery_app --broker=$CELERY_BROKER_URL
          --loglevel=info --autoscale=5,1
        - flower -A flask_app.worker.tasks.celery_app --broker=$CELERY_BROKER_URL
          --port=5555
        command:
        - /bin/bash
        - -c
        env:
        - name: USER
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-credentials
        - name: PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-credentials
        - name: IP
          value: postgres
        - name: SECRET_CODE
          value: ${{ secrets.GITHUB_TOKEN }}
        - name: DB
          valueFrom:
            secretKeyRef:
              key: user
              name: postgres-credentials
        - name: BROKER_USER
          valueFrom:
            secretKeyRef:
              key: rabbitmq_user
              name: flask-credentials
        - name: BROKER_PASS
          valueFrom:
            secretKeyRef:
              key: rabbitmq_pass
              name: flask-credentials
        - name: CELERY_BROKER_URL
          value: amqp://$(BROKER_USER):$(BROKER_PASS)@rabbitmq-service:5672
        image: docker.pkg.github.com/claudezss/myapi/backend:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - echo 123123
        name: worker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerconfigjson-github-com
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
