
name: Tests and Build

jobs:
  tests:
    runs-on: ubuntu-latest
    on: push
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black isort
        pip install -r requirements.txt 
        
    - name: Lint with flake8
      run: |
        flake8
    - name: Lint with back
      run: |
        black
    - name: Lint wiht isort
      run: |
        isort
    - name: Test with pytest
      run: |
        pytest -s tests/unit_tests

  build:
    on:
      push:
        branches: [ master ]

    runs-on: ubuntu-latest

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        # Runs a single command using the runners shell
        - name: Push to GitHub Packages
          uses: docker/build-push-action@v1
          with:
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
            registry: docker.pkg.github.com
            repository: claudezss/claudezhang/backend
            tag_with_ref: true
