
name: "Build and Release"

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: claudezss/claudezhang/backend
          tag_with_ref: true'

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.HOST_PASS }}
          port: 22
          script: |
            cd /home/claude/claudezhang
            git pull
            export GMAIL_USER=${{secrets.GMAIL_USER}}
            export GMAIL_PASS=${{secrets.GMAIL_PASS}}
            docker-compose up -d
