
name: "Build and Release"

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: claudezss/myapi/backend
          tag_with_ref: true
          
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save b8025a39-472e-4746-84ed-18b7ec5cdb31
         
      - name: Deploy flask
        run: |
          template=`cat "deploy/myapi.yaml.template" | sed -e "s/{{TAG}}/${{ github.event.release.tag_name }}; s/{{CODE}}/${{secrets.CODE}}/g; s/{{AWS_KEY}}/${{secrets.AWS_KEY}}/g; s/{{AWS_SECRET}}/${{secrets.AWS_SECRET}}/g; s/{{SPACE_NAME}}/'${{secrets.SPACE_NAME}}'/g; s/{{SPACE_ENDPOINT}}/'${{secrets.SPACE_ENDPOINT}}'/g; s/{{SPACE_REGION}}/${{secrets.SPACE_REGION}}/g"`
          echo "$template" | kubectl apply -f -
